ecommerce/core/urls.py
from django.urls import path
from .views import *

app_name = 'ecommerce'
urlpatterns = [
            path('home/',HomeView.as_view(),name='Item-list'),
            path('seller/',SellerView,name='Seller'),
            path('checkout/',cart,name='Checkout'),
            path('order-summary/',OrderSummaryView.as_view(),name='order-summary'),
            path('product/<slug>/',ItemDetailView.as_view(),name="product"),
            path('add-to-cart/<slug>/',add_to_cart,name="add-to-cart"),
            path('remove-from-cart/<slug>/',remove_from_cart,name="remove-from-cart")
        ] 

ecommerce/ecommerce/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static 
app_name = 'ecommerce'
urlpatterns = [
    path('admin/', admin.site.urls),
    path('main/',include('core.urls',namespace='core')),
    path('',include('playground.urls',namespace='start')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT) # New

ecommerce/playground/urls.py
from django.urls import path
from . import views

app_name = 'ecommerce'
urlpatterns = [
    path('hello/',views.say_hello),
    path('loginn/',views.login_request,name='login'),
    path('signup/',views.signup,name='signup'),  
    path('logout/',views.logout_user,name='logout'),
]

playground/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('hello/',views.say_hello),
    path('login/',views.login,name='login'),
    path('signup/',views.signup,name='signup')    
]

storefront/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('playground/',include('playground.urls'))
]

ecommerce/core/models.py
import uuid
from django.conf import settings
from django.contrib.auth.models import User
from django.shortcuts import reverse
from django.views.generic import ListView,DetailView
from django.db import models
from playground.models import *
# Create your models here.
CAT_CHOICES = (
        ('S','Shirt'),
        ('SW','Spots wear'),
        ('OW','Outwear')
    )

LABLE_CHOICES= (
        ('P',"primary"),
        ('S',"secondary"),
        ('D',"danger"),
    )
STATUS_CHOICES= (
        ('NP',"Not Processed"),
        ('P',"Processing"),
        ('OD',"Out for Delivery"),
        ('D',"Delivered"),
    )

# user_group = User.objects.filter(groups_name='user') 
# user_group = user_group.user_set.all()
# seller_group = User.objects.filter(groups_name='seller') 
# seller_group = seller_group.user_set.all()
user_group = User
seller_group = User
class Items(models.Model):
    title = models.CharField(max_length=200)
    price = models.FloatField()
    category = models.CharField(choices=CAT_CHOICES,max_length=2)
    label = models.CharField(choices=LABLE_CHOICES,max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    
    seller_id = models.IntegerField(default=-1)
    image = models.ImageField(upload_to='images',default=None) 
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return self.title
    pass

    def get_absolute_url(self):
        return reverse("core:product",kwargs={
                'slug': self.slug
            })

    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart",kwargs={
                'slug': self.slug
            })

    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart",kwargs={
                'slug': self.slug
            })

class SellerOrders(models.Model):
    order_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    seller_id = models.IntegerField(default=-1,unique=False)
    item_id = models.IntegerField(default=-1)
    customer_name = models.CharField(max_length=30,default=None)
    customer_address = models.CharField(max_length=200,default=None)
    customer_email = models.EmailField(default=None)

    def __str__(self):
        return f"seller id - {self.seller_id} has"


class Orderitems(models.Model):
    user = models.ForeignKey(user_group,on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Items,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    status = models.CharField(choices=STATUS_CHOICES,max_length=2) 

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"
    pass

class Order(models.Model):
    user = models.ForeignKey(user_group,on_delete=models.CASCADE)
    items = models.ManyToManyField(Orderitems)
    start_date = models.DateTimeField(auto_now=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)
    pass

ecommerce/core/views.py
from django.contrib import messages
from django.utils import timezone
from django.shortcuts import redirect, render,get_object_or_404
from django.http import HttpResponse
from django.views.generic import ListView,DetailView
from .models import *
from .filter import *

# Create your views here.
def message(msg):
    print("################################################")
    print()
    print(msg)
    print()
    print("################################################")

def SellerView(request):
    sellerOrder =  SellerOrders.objects.all()
    totalOrder = 0
    totalOrder = 0
    
    totalRevenue = 0
    allowed_sellerOrder = []
    for so in sellerOrder:
        print(request.user.id,end=" - ")
        print(so.seller_id)
        print(so.seller_id == request.user.pk)
        if so.seller_id != request.user.pk:
            continue
        totalOrder+=1
        allowed_sellerOrder.append(so)
        item = Items.objects.filter(pk = so.item_id)[0]
        totalRevenue+=item.price
    print("Total Revenue is ",totalRevenue)
    print("Total order is ",totalOrder)

    
    context={
            'object_list': allowed_sellerOrder,
            'total_orders': totalOrder,
            'total_revenue': totalRevenue,
            }
    return render(request,"sellerOrder.html",context)


class HomeView(ListView):
    model = Items 
    template_name="home-page.html"
    filterset_class = ItemFilter
    def get_queryset(self):
        query_set = super().get_queryset()
        self.filterset = self.filterset_class(self.request.GET,queryset=query_set)
        return self.filterset.qs.distinct()

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['Filterset'] = self.filterset
        return context


class ItemDetailView(DetailView):
    model= Items
    template_name="product-page.html"

class OrderSummaryView(DetailView):
    model = Order 
    template_name = "order-summary.html"

def add_to_cart(request,slug):
    item = get_object_or_404(Items,slug=slug) 
    order_item , created = Orderitems.objects.get_or_create(
            item=item,
            user=request.user,
            ordered=False
        )
    order_qs = Order.objects.filter(user=request.user,ordered=False)

    if order_qs.exists():
        order = order_qs[0]
        # check is the item is already in the cart
        if order.items.filter(item__slug=item.slug).exists():
            order_item.quantity+=1
            order_item.save()
            messages.info(request,"This item quantity was updated")
        else:
            messages.info(request,"This item was added in cart")
            order.items.add(order_item)
    else:
        ordered_date = timezone.now()
        order = Order.objects.create(user=request.user,ordered_date=ordered_date)
        order.items.add(order_item)
        messages.info(request,"The order item was added")

    return redirect("core:product",slug=slug)

def remove_from_cart(request,slug):
    item = get_object_or_404(Items,slug=slug)
    order_qs = Order.objects.filter(user=request.user,ordered=False)
    print("----------------------------------------------------------")
    print(order_qs)
    print("----------------------------------------------------------")
    if order_qs.exists():
        order = order_qs[0]
        if order.items.filter(item__slug=item.slug).exists():
            d = order.items.filter(item__slug=item.slug)
            d.delete()
            # order_item = Orderitems.objects.filter(
            #         item=item,
            #         user=request.user,
            #         ordered=False
            #         )[0]
            # order.items.remove(order_item)
            messages.info(request,"item was removed from your cart")
            return redirect("core:Checkout")
        else:
            # the order item does not exists
            messages.info(request,"item is does not exist in the cart")
            return redirect("core:Checkout")
    else:
        # tell user that he doesnt have a product
        messages.info(request,"User doesnt have an order")
        return redirect("core:Checkout")



def cart(request):
    order_qs = Order.objects.filter(user=request.user)
    items = order_qs[0].items.all()
    try:
        # marking all as ordered 
        if request.method=="POST":
            print("MAking post request")
            f_name = request.POST.get('firstname')
            l_name = request.POST.get('lastname')
            name = f_name+" "+l_name
            print(request.POST)

            email = request.POST.get('email')
            address = request.POST.get('address')
            country = request.POST.get('country')
            state = request.POST.get('state')
            email = request.POST.get('email')
            zip = request.POST.get('zip')

            final_address = address+","+str(country)+","+str(state)+","+str(zip)
            
            for i in items:
                item = Items.objects.get(pk = i.item.pk)
                print(item)
                item.quantity = i.item.quantity
                seller = SellerOrders.objects.create(
                        seller_id = i.item.seller_id,
                        item_id = i.item.pk,
                        customer_name = name ,
                        customer_address = final_address,
                        customer_email = email 
                        )

                i.ordered = True
                i.delete()
                print(seller)
        # adding that in seller order

            messages.info(request,"Your Order Has been Placed")
            return redirect("core:Item-list")
    except Exception as e:
        print(e)

    total_amt = 0
    for i in items:
        print(i.item)
        i.item.price *= i.quantity
        total_amt+= i.item.price 
    context = {
            'items': items,
            'total_amt': total_amt
            }
    return render(request,"checkout-page.html",context)

def product_page(request):
    return render(request,"product-page.html")

ecommerce/core/templates/home-page.html
{% extends "base.html"%}
{% load bootstrap_icons %}{# Load the tag library #}


{% block home%}
<!--Main layout-->
<main>
  <div class="container" style="margin-top:100px;" >

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">
        <form method="get">
          <div class="" style="display:flex;width:137%;flex-wrap: nowrap;  text-align: center;
  line-height:100%;">
            <div class="col" style="text-align: center;line-height:100%;">
              <span>Name</span>
                  {{Filterset.form.title}}
            </div>
            <div class="col" style="text-align: center;line-height:100%;">
              <span>Category <br> </span>
                  {{Filterset.form.category}}
            </div>
            <div class="col " style="text-align: center; line-height:100%;" >
              <span>label      <br> </span> {{Filterset.form.label}}
            </div>
            <div class="col">
              <button class="btn " style="background-color:white;border-radius:20px;" type="submit">
                  GO
                </button>
            </div>
          </div>
        </form>

      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <!--Grid row-->
      <div class="row wow fadeIn">

        {% for item in object_list %}
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4">

          <!--Card-->
          <div class="card" >

            <!--Card image-->
            <div class="view overlay">
              <img src="{{item.image.url}}" class="card-img-top"
                alt="">
              <a href="{{item.get_absolute_url}}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              <a href="" class="grey-text">
                <h5>{{item.get_category_display}}</h5>
              </a>
              <h5>
                <strong>
                  <a href="" class="dark-grey-text">{{item.title}}
                    <span class="badge badge-pill {{item.get_label_display}}-color">NEW</span>
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>{{item.price}}</strong>
              </h4>

            </div>
            <!--Card content-->

          </div>
          <!--Card-->

        </div>
        <!--Grid column-->
        {%endfor%}

        <!--Grid column-->

      </div>
      <!--Grid row-->


    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->
    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        <!--Arrow left-->
        {% if page_obj.has_previous %}
        <li class="page-item disabled">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {%endif%}

        <li class="page-item active">
          <a class="page-link" href="#">1
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">4</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">5</a>
        </li>

        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul>
    </nav>
    {%endif%}
    <!--Pagination-->

  </div>
</main>
<!--Main layout-->
{%endblock%}
   

ecommerce/core/templates/items.html
{% extends "base.html" %}
{% block contents %}
<h1>Here is the list</h1>

<h2>Print</h2>
{% for item in items %}
{{ item.title }} - {{item.price}}<br>
{% endfor %}
{% block footer %}
{% endblock %}


{% endblock contents %}

ecommerce/core/templates/navbar.html
{% load static %}
  <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar">
    <div class="container">

      <!-- Brand -->
      <a class="navbar-brand waves-effect" href="{% url 'core:Item-list'%}">
        <strong class="blue-text">SuperStore</strong>
      </a>

      <!-- Collapse -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Links -->
      <div class="collapse navbar-collapse" id="navbarSupportedContent">

        <!-- Left -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link waves-effect" href="{%url 'core:Item-list'%}">Home
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link waves-effect" arget="_blank">About</a>
          </li>
        
        </ul>

        <!-- Right -->
        <ul class="navbar-nav nav-flex-icons">
          {%if request.user.is_authenticated%}
          <li class="nav-item">
            <a class="nav-link waves-effect" href="{%url 'core:Checkout'%}">
              <i class="fas fa-shopping-cart"></i>
              <span class="clearfix d-none d-sm-inline-block"> Cart </span>
            </a>
          </li>
          <li class="nav-item">
              <!-- <span class="clearfix d-none d-sm-inline-block"> Logout </span> -->
              <a href="{% url 'start:logout' %}" style="margin-top:8px;margin-left:5px">Logout</a>
            </a>
          </li>
          {%else%}
          <li class="nav-item">
              <span class="clearfix d-none d-sm-inline-block"> Login </span>
            </a>
          </li>
          <li class="nav-item">
            <!-- <a class="nav-link waves-effect" href="{}"> -->
              <span class="clearfix d-none d-sm-inline-block"> SignUp </span>
            </a>
          </li>
          {%endif%}
        </ul>

      </div>

    </div>
  </nav>

ecommerce/core/templates/order-summary.html
{% extends "base.html"%}

{% block home%}
<!--Main layout-->
<main>
  <div class="container" style="margin-top:100px;" >

    <!--Navbar-->
    <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

      <!-- Navbar brand -->
      <span class="navbar-brand">Categories:</span>

      <!-- Collapse button -->
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
        aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <!-- Collapsible content -->
      <div class="collapse navbar-collapse" id="basicExampleNav">

        <!-- Links -->
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#">All
              <span class="sr-only">(current)</span>
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Shirts</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Sport wears</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Outwears</a>
          </li>

        </ul>
        <!-- Links -->

        <form class="form-inline">
          <div class="md-form my-0">
            <input class="form-control mr-sm-2" type="text" placeholder="Search" aria-label="Search">
          </div>
        </form>
      </div>
      <!-- Collapsible content -->

    </nav>
    <!--/.Navbar-->

    <!--Section: Products v.3-->
    <section class="text-center mb-4">

      <!--Grid row-->
      <div class="row wow fadeIn">

        {% for item in object_list %}
        <!--Grid column-->
        <div class="col-lg-3 col-md-6 mb-4">

          <!--Card-->
          <div class="card" >

            <!--Card image-->
            <div class="view overlay">
              <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top"
                alt="">
              <a href="{{item.get_absolute_url}}">
                <div class="mask rgba-white-slight"></div>
              </a>
            </div>
            <!--Card image-->

            <!--Card content-->
            <div class="card-body text-center">
              <!--Category & Title-->
              <a href="" class="grey-text">
                <h5>{{item.get_category_display}}</h5>
              </a>
              <h5>
                <strong>
                  <a href="" class="dark-grey-text">{{item.title}}
                    <span class="badge badge-pill {{item.get_label_display}}-color">NEW</span>
                  </a>
                </strong>
              </h5>

              <h4 class="font-weight-bold blue-text">
                <strong>{{item.price}}</strong>
              </h4>

            </div>
            <!--Card content-->

          </div>
          <!--Card-->

        </div>
        <!--Grid column-->
        {%endfor%}

        <!--Grid column-->

      </div>
      <!--Grid row-->


    </section>
    <!--Section: Products v.3-->

    <!--Pagination-->
    {% if is_paginated %}
    <nav class="d-flex justify-content-center wow fadeIn">
      <ul class="pagination pg-blue">

        <!--Arrow left-->
        {% if page_obj.has_previous %}
        <li class="page-item disabled">
          <a class="page-link" href="#" aria-label="Previous">
            <span aria-hidden="true">&laquo;</span>
            <span class="sr-only">Previous</span>
          </a>
        </li>
        {%endif%}

        <li class="page-item active">
          <a class="page-link" href="#">1
            <span class="sr-only">(current)</span>
          </a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">2</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">3</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">4</a>
        </li>
        <li class="page-item">
          <a class="page-link" href="#">5</a>
        </li>

        <li class="page-item">
          <a class="page-link" href="#" aria-label="Next">
            <span aria-hidden="true">&raquo;</span>
            <span class="sr-only">Next</span>
          </a>
        </li>
      </ul>
    </nav>
    {%endif%}
    <!--Pagination-->

  </div>
</main>
<!--Main layout-->
{%endblock%}
   

ecommerce/core/templates/product-page.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta http-equiv="x-ua-compatible" content="ie=edge">
  <title> Ecommerce Website </title>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
  <!-- Bootstrap core CSS -->
  <link href="{% static 'core/css/bootstrap.min.css'%}" rel="stylesheet">
  <!-- Material Design Bootstrap -->
  <link href="{% static 'core/css/mdb.min.css'%}" rel="stylesheet">
  <!-- Your custom styles (optional) -->
  <link href="{% static 'core/css/style.min.css'%}" rel="stylesheet">
</head>

<body>

  {%include 'navbar.html'%}
  <!-- <!-- Navbar --> -->
  <!-- <nav class="navbar fixed-top navbar-expand-lg navbar-light white scrolling-navbar"> -->
  <!--   <div class="container"> -->

  <!--     <!-- Brand --> -->
  <!--     <a class="navbar-brand waves-effect" href="/" > -->
  <!--       <strong class="blue-text">SuperStore</strong> -->
  <!--     </a> -->

  <!--     <!-- Collapse --> -->
  <!--     <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" -->
  <!--       aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"> -->
  <!--       <span class="navbar-toggler-icon"></span> -->
  <!--     </button> -->

  <!--     <!-- Links --> -->
  <!--     <div class="collapse navbar-collapse" id="navbarSupportedContent"> -->

  <!--       <!-- Left --> -->
  <!--       <ul class="navbar-nav mr-auto"> -->
  <!--         <li class="nav-item"> -->
  <!--           <a class="nav-link waves-effect" href="/about" target="_blank">About</a> -->
  <!--         </li> -->
  <!--       </ul> -->

  <!--       <!-- Right --> -->
  <!--       <ul class="navbar-nav nav-flex-icons"> -->
  <!--         <li class="nav-item"> -->
  <!--           <a class="nav-link waves-effect"> -->
  <!--             <span class="badge red z-depth-1 mr-1"> 1 </span> -->
  <!--             <i class="fas fa-shopping-cart"></i> -->
  <!--             <span class="clearfix d-none d-sm-inline-block"> Cart </span> -->
  <!--           </a> -->
  <!--         </li> -->
  <!--       </ul> -->

  <!--     </div> -->

  <!--   </div> -->
  <!-- </nav> -->
  <!-- Navbar -->
  {% if messages %}
  <div class="mt-5 pt-4">
      {% for message in messages %}
      <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
      {{message}}
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
      </button>
      </div>
      {% endfor %}
    
  </div>
  {% endif %}

  <!--Main layout-->
  <main class="mt-5 pt-4">
    <div class="container dark-grey-text mt-5">

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <img src="{{object.image.url}}" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-md-6 mb-4">

          <!--Content-->
          <div class="p-4">

            <div class="mb-3">
              <h2>{{object.title}}</h2>
              <a href="">
                <span class="badge purple mr-1">{{object.get_category_display}}</span>
              </a>
              <a href="">
                <span class="badge blue mr-1">New</span>
              </a>
              <!-- <a href=""> -->
              <!--   <span class="badge red mr-1">Bestseller</span> -->
              <!-- </a> -->
            </div>

            <p class="lead">
              <!-- <span class="mr-1"> -->
              <!--   <del>$200</del> -->
              <!-- </span> -->
              <span>${{object.price}}</span>
            </p>

            <p class="lead font-weight-bold">Description</p>

            <p>{{object.description}}</p>

            <!-- <form class="d-flex justify-content-left"> -->
            <!--    Default input -->
            <!--   <input type="number" value="1" aria-label="Search" class="form-control" style="width: 100px"> -->
            <!--   <button class="btn btn-primary btn-md my-0 p" type="submit">add to cart -->
            <!--     <i class="fas fa-shopping-cart ml-1"></i> -->
            <!--   </button> -->

            <!-- </form> -->
            <a href={{object.get_add_to_cart_url}} class="btn btn-primary btn-md my-0 p" >add to cart
                <i class="fas fa-shopping-cart ml-1"></i>
            </a>

          </div>
          <!--Content-->

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <hr>

      <!--Grid row-->
      <div class="row d-flex justify-content-center wow fadeIn">

        <!--Grid column-->
        <div class="col-md-6 text-center">

          <h4 class="my-4 h4">Additional information</h4>

          <p>Lorem ipsum dolor sit amet consectetur adipisicing elit. Natus suscipit modi sapiente illo soluta odit
            voluptates,
            quibusdam officia. Neque quibusdam quas a quis porro? Molestias illo neque eum in laborum.</p>

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

      <!--Grid row-->
      <div class="row wow fadeIn">

        <!--Grid column-->
        <div class="col-lg-4 col-md-12 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/11.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/12.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

        <!--Grid column-->
        <div class="col-lg-4 col-md-6 mb-4">

          <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Products/13.jpg" class="img-fluid" alt="">

        </div>
        <!--Grid column-->

      </div>
      <!--Grid row-->

    </div>
  </main>
  <!--Main layout-->

  <!--Footer-->
  <footer class="page-footer text-center font-small mt-4 wow fadeIn">



    <!--Copyright-->
    <div class="footer-copyright py-3">
      © 2019 Copyright:
      <a href="/" target="_blank"> SuperStore.com </a>
    </div>
    <!--/.Copyright-->

  </footer>
  <!--/.Footer-->

  <!-- SCRIPTS -->
  <!-- JQuery -->
  <script type="text/javascript" src="{% static 'core/js/jquery-3.4.1.min.js'%}"></script>
  <!-- Bootstrap tooltips -->
  <script type="text/javascript" src="{% static 'core/js/popper.min.js'%}"></script>
  <!-- Bootstrap core JavaScript -->
  <script type="text/javascript" src="{% static 'core/js/bootstrap.min.js'%}"></script>
  <!-- MDB core JavaScript -->
  <script type="text/javascript" src="{% static 'core/js/mdb.min.js'%}"></script>
  <!-- Initializations -->
  <script type="text/javascript">
    // Animations initialization
    new WOW().init();

  </script>
</body>

</html>